; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Multiwinia Hardware Compatibility
AppVerName=Multiwinia Hardware Compatibility v1.9.7
AppPublisher=Introversion Software Ltd
Compression=zip/5
DefaultDirName={pf}\Multiwinia Hardware Compatibility
DefaultGroupName=Multiwinia Hardware Compatibility
LicenseFile=..\docs\IntroversionEULA.txt
OutputBaseFilename=setup
SetupIconFile=..\targets\vs2005\darwinia.ico

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkablealone

[Files]
Source: "..\build\multiwinia.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\init.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\language.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\main.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\menusounds.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\sounds.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\sounds2.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\ncftpput.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\MultiwiniaSupport.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\MultiwiniaSupport.ini"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\dbghelp.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Multiwinia Hardware Compatibility"; Filename: "{app}\multiwinia.exe"; WorkingDir: "{app}"
Name: "{group}\Multiwinia Website"; Filename: "http://www.multiwinia.co.uk/"
; Name: "{group}\Support Website"; Filename: "http://www.multiwinia.co.uk/support"
Name: "{group}\Support Website"; Filename: "http://forums.introversion.co.uk/multiwinia/"
Name: "{group}\{cm:UninstallProgram,Multiwinia Hardware Compatibility}"; Filename: "{uninstallexe}"
Name: "{userdesktop}\Multiwinia Hardware Compatibility"; Filename: "{app}\multiwinia.exe"; WorkingDir: "{app}"; Tasks: desktopicon

[UninstallDelete]
Type: filesandordirs; Name: "{app}\users"
Type: filesandordirs; Name: "{app}\benchmarks"
Type: filesandordirs; Name: "{app}\screenshots"
Type: files; Name: "{app}\preferences.txt"
Type: files; Name: "{app}\authkey"
Type: files; Name: "{app}\debug.txt"
Type: files; Name: "{app}\inputprefs_debug.txt"
Type: files; Name: "{app}\userprefs.txt"
Type: files; Name: "{app}\game-history.txt"
Type: files; Name: "{app}\blackbox.txt"
Type: files; Name: "{app}\dxdiag.txt"
Type: files; Name: "{app}\CRASH.DMP"
Type: files; Name: "{app}\ERRORLOG.TXT"
Type: files; Name: "{app}\dxdiag_info.txt"
Type: files; Name: "{app}\multiwinia.zip"
Type: files; Name: "{app}\multiwinia.zip.0001"
Type: files; Name: "{app}\multiwinia.zip.0002"
Type: files; Name: "{app}\multiwinia.zip.0003"
Type: files; Name: "{app}\multiwinia.zip.0004"
Type: files; Name: "{app}\multiwinia.zip.0005"
Type: files; Name: "{app}\multiwinia.zip.0006"
Type: files; Name: "{app}\multiwinia.zip.0007"
Type: files; Name: "{app}\multiwinia.zip.0008"
Type: files; Name: "{app}\multiwinia.zip.0009"
Type: files; Name: "{app}\multiwinia.zip.0010"
Type: files; Name: "{app}\multiwinia.zip.0011"
Type: files; Name: "{app}\multiwinia.zip.0012"
Type: files; Name: "{app}\multiwinia.zip.0013"
Type: files; Name: "{app}\multiwinia.zip.0014"
Type: files; Name: "{app}\multiwinia.zip.0015"
Type: files; Name: "{app}\multiwinia.zip.0016"
Type: files; Name: "{app}\multiwinia.zip.0017"
Type: files; Name: "{app}\multiwinia.zip.0018"
Type: files; Name: "{app}\multiwinia.zip.0019"
Type: files; Name: "{app}\multiwinia.zip.0020"
Type: files; Name: "{app}\multiwinia.zip.0021"
Type: files; Name: "{app}\multiwinia.zip.0022"
Type: files; Name: "{app}\multiwinia.zip.0023"
Type: files; Name: "{app}\multiwinia.zip.0024"
Type: files; Name: "{app}\multiwinia.zip.0025"
Type: files; Name: "{app}\multiwinia.zip.0026"
Type: files; Name: "{app}\multiwinia.zip.0027"
Type: files; Name: "{app}\multiwinia.zip.0028"
Type: files; Name: "{app}\multiwinia.zip.0029"
Type: files; Name: "{app}\multiwinia.zip.0030"
Type: files; Name: "{app}\multiwinia.zip.0031"
Type: files; Name: "{app}\multiwinia.zip.0032"
