; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Multiwinia
AppVerName=Multiwinia v1.9.20
AppPublisher=Introversion Software Ltd
Compression=zip/5
DefaultDirName={pf}\Multiwinia
DefaultGroupName=Multiwinia
LicenseFile=..\docs\IntroversionEULA.txt
OutputBaseFilename=setup
SetupIconFile=..\targets\vs2005\darwinia.ico

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkablealone

[Files]
Source: "..\build\multiwinia.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\init.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\language.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\main.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\menusounds.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\sounds.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\sounds2.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\ambx.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\dbghelp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\autopatch.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\copy_assist.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\version"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\origin"; DestDir: "{app}"; Flags: ignoreversion onlyifdoesntexist
; Source: "..\build\manual.pdf"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\ProfileLocator.exe"; DestDir: "{app}"; Flags: ignoreversion

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Multiwinia"; Filename: "{app}\autopatch.exe"; WorkingDir: "{app}"
Name: "{group}\Repair Multiwinia"; Filename: "{app}\autopatch.exe"; WorkingDir: "{app}"; Parameters: "--repair"
Name: "{group}\Multiwinia Website"; Filename: "http://www.multiwinia.co.uk/"
Name: "{group}\Support Website"; Filename: "http://www.multiwinia.co.uk/support"
; Name: "{group}\Manual (PDF)"; Filename: "{app}\manual.pdf"
Name: "{group}\Open Multiwinia Profile"; Filename: "{app}\ProfileLocator.exe"; WorkingDir: "{app}"
Name: "{group}\{cm:UninstallProgram,Multiwinia}"; Filename: "{uninstallexe}"
Name: "{userdesktop}\Multiwinia"; Filename: "{app}\autopatch.exe"; WorkingDir: "{app}"; Tasks: desktopicon

[UninstallDelete]
Type: filesandordirs; Name: "{app}\users"
Type: filesandordirs; Name: "{app}\benchmarks"
Type: filesandordirs; Name: "{app}\screenshots"
Type: files; Name: "{app}\preferences.txt"
Type: files; Name: "{app}\authkey"
Type: files; Name: "{app}\debug.txt"
Type: files; Name: "{app}\syncerror-*.txt"
Type: files; Name: "{app}\inputprefs_debug.txt"
Type: files; Name: "{app}\userprefs.txt"
Type: files; Name: "{app}\game-history.txt"
Type: files; Name: "{app}\blackbox.txt"
Type: files; Name: "{app}\dxdiag.txt"
Type: files; Name: "{app}\stdout.txt"
Type: files; Name: "{app}\autopatch_debug.txt"
Type: files; Name: "{app}\copier_stdout.txt"
Type: files; Name: "{app}\copier_debug.txt"
Type: filesandordirs; Name: "{app}\backup_*"
Type: filesandordirs; Name: "{app}\revert_*"
Type: files; Name: "{app}\CRASH.DMP"
Type: files; Name: "{app}\ERRORLOG.TXT"
