# -*- Makefile -*- for Darwinia

#
# In the parent directory of code/ contrib/ targets/
#
# make -f targets/linux/Makefile
# 

CXXFLAGS=-g

CPPFLAGS=\
-DTARGET_OS_LINUX \
-DHAVE_SOCKET \
-DHAVE_SELECT \
-DHAVE_GETHOSTBYNAME \
-DHAVE_INET_NTOA \
-Icode 

# CONTRIBDEPS=\
# contrib/unrar/libunrar.a\
# contrib/netclass/libnetclass.a

# $(CONTRIBDEPS):
# 	@echo "Building contrib dependency: " $@
# 	@$(MAKE) -C $(dir $@) $(notdir $@)

LIBS=

LINK=c++
STRIP=strip

# Sources

SOURCES=\
code/keygen.cpp	\
tools/PasswordGenerator/main.cpp

# Building 

OBJDIR=.linux-objs
OBJECTS=$(OBJDIR)/$(SOURCES:%.cpp=%.o)

$(OBJDIR)/%.o: %.cpp
	@test -d $(dir $(OBJDIR)/$<) || mkdir -p $(dir $(OBJDIR)/$<)
	@echo Compiling $<
	@$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@

keygen-1: $(OBJECTS)
	@echo -n "Linking... "
	$(LINK) -o $@ $(LIBS) $+
	$(STRIP) $@
	
update: keygen-1
	@echo Update keygen-1 on server
	scp keygen-1 root@www.introversion.co.uk:/home/package/darwinia/win32_beta1/keygen

# Automatic Dependencies
DEPENDDIR = .linux-depend
$(DEPENDDIR)/%.d: %.cpp
	@echo make-depend $<
	@mkdir -p $(dir $@) 2> /dev/null
	@$(CC) -MM $(CPPFLAGS) $< | \
	( IFS=':' ; read target deps ; \
          echo $(OBJDIR)/$(<:.cpp=.o) $@\:$$deps ) > $@

autodependencies = $(patsubst %.cpp,$(DEPENDDIR)/%.d,$(SOURCES))
include $(autodependencies)

